Devolutions/picky-rs

Cargo.lock
picky/Cargo.toml
picky/src/http/http_signature.rs
picky/src/http/mod.rs

- builder do not add spaces between fields of the produced signature
- builder do not add quotes on integers (eg: created=2923983 instead of
created="2923983")
- parser supports values with quotes or no quotes at all regardless of
the parameter
That is, produced HTTP signatures by builder are now like:
```
Signature
keyId="my-rsa-key",created=1402170695,headers="(request-target)
(created) date",signature="..."
```
Parser can read anything like above and even weirdly formatted
signatures like:
```
Signature keyId = my-rsa-key, created=
"1402170695",headers=(request-target) (created) date, signature=...
```
You can build a legacy HTTP signature by calling the `legacy` method on the HTTP Signature builder (see legacy test).

HTTP signature parser and builder legacy support

---

Cargo.lock
picky-server/Cargo.toml

4.4.0 has been released. Version bump to 4.5.0 to prepare next cycle

Version bump from 4.4.0 to 4.5.0

---

Cargo.lock

This fixes a vulnerability reported by `cargo audit`.
```
ID:       RUSTSEC-2020-0006
Crate:    bumpalo
Version:  3.2.0
Date:     2020-03-24
URL:      https://rustsec.org/advisories/RUSTSEC-2020-0006
Title:    Flaw in `realloc` allows reading unknown memory
Solution:  upgrade to >= 3.2.1
Dependency tree: 
bumpalo 3.2.0
└── wasm-bindgen-backend 0.2.59
└── wasm-bindgen-macro-support 0.2.59
└── wasm-bindgen-macro 0.2.59
└── wasm-bindgen 0.2.59
├── web-sys 0.3.36
│   ├── wasm-bindgen-futures 0.4.9
│   │   └── reqwest 0.10.4
│   │       └── picky-server 4.5.0
│   ├── reqwest 0.10.4
│   └── plotters 0.2.12
│       └── criterion 0.3.1
│           └── picky-server 4.5.0
├── wasm-bindgen-futures 0.4.9
├── reqwest 0.10.4
├── plotters 0.2.12
└── js-sys 0.3.36
├── web-sys 0.3.36
├── …
```

Update bumpalo dependency

---

picky-server/src/cli.yml
picky-server/src/config.rs
picky-server/src/db/mongodb/mod.rs
picky-server/src/db/mongodb/mongo_connection.rs

Idem a den-server, il pourrait être pratique de spécifier le nom de la BD a utiliser.  Le défaut demeure picky.

Added PICKY_DB_NAME to be able to specify database name

---

picky-asn1-x509/src/private_key_info.rs
picky/Cargo.toml
picky/src/key.rs

RFC 8017 can be found here:
https://tools.ietf.org/html/rfc8017.html
It defines RSA private keys like so:
RSAPrivateKey ::= SEQUENCE {
version           Version,
modulus           INTEGER,  -- n
publicExponent    INTEGER,  -- e
privateExponent   INTEGER,  -- d
prime1            INTEGER,  -- p
prime2            INTEGER,  -- q
exponent1         INTEGER,  -- d mod (p-1)
exponent2         INTEGER,  -- d mod (q-1)
coefficient       INTEGER,  -- (inverse of q) mod p
otherPrimeInfos   OtherPrimeInfos OPTIONAL
}
Previously, the implementation of RSA private keys in picky omitted:
- exponent1
- exponent2
- coefficient
- otherPrimeInfos
This commit modifies the RSAPrivateKey struct to include these fields,
as well as changes the struct to be more runtime safe.

Modify RSAPrivateKey to be RFC 8017 compliant

---

Cargo.lock
picky-server/CHANGELOG.md
picky-server/Cargo.toml

Version 4.8.0 released... moving to next version

picky-server: version bump to 4.9.0

---

picky-asn1-x509/Cargo.toml
picky-asn1-x509/src/certification_request.rs
picky-asn1-x509/src/directory_string.rs
picky-asn1-x509/src/macros.rs
picky-asn1-x509/src/oids.rs
picky/Cargo.toml

Address #77 , on behalf of Isode Ltd.
Some precision on this PR:
the `attributes` field ended up being `Implicit<Option<ApplicationTag0<Attribute>>>` instead of 
`Implicit<Option<ApplicationTag0<Asn1SetOf<Attribute>>>>` because after testing the output of openssl, it seems that the Asn1SetOf is not present.
using the attached files, you can use
`openssl req -config req.txt -new -key key.pem -out req.pem` 
to generate the CSR and see that there's no `SET` after `[0]`
I was curious on what's the output of openssl if we add a challengePassword to the request: add `attributes = req_attributes` to the `[ req ]` section and rerun the openssl command, you'll see:
so after the `[0]`, no `SET` and two consecutive `SEQUENCE`.
We don't need challengePassword yet, but if we add support later, I think …

Add extension request support

---

Cargo.lock
Cargo.toml
picky-asn1-der/Cargo.toml
picky-asn1-x509/Cargo.toml
picky-asn1/Cargo.toml
picky-signtool/Cargo.toml
picky-signtool/src/main.rs
picky/Cargo.toml

picky-signtool uses picky Authenticode implementation and lief-rs for embedding an Authenticode signature to the target binary.

Implement picky-signtool

---

Cargo.lock
picky-asn1-der/Cargo.toml
picky-asn1-der/src/de/mod.rs
picky-asn1-der/src/raw_der.rs
picky-asn1-der/src/ser/mod.rs
picky-asn1-der/tests/pki_tests/version.rs
picky-asn1-der/tests/pki_tests/x509_v3_certificate.rs
picky-asn1-der/tests/serde_der_advanced_asn1_types.rs
picky-asn1-der/tests/serde_der_sequence.rs
picky-asn1-x509/Cargo.toml
picky-asn1-x509/src/attribute.rs
picky-asn1-x509/src/certificate.rs
picky-asn1-x509/src/certification_request.rs
picky-asn1-x509/src/extension.rs
picky-asn1-x509/src/name.rs
picky-asn1-x509/src/pkcs7.rs
picky-asn1-x509/src/pkcs7/content_info.rs
picky-asn1-x509/src/pkcs7/crls.rs
picky-asn1-x509/src/pkcs7/signed_data.rs
picky-asn1-x509/src/pkcs7/signer_info.rs
picky-asn1-x509/src/version.rs
picky-asn1/CHANGELOG.md
picky-asn1/Cargo.toml
picky-asn1/src/tag.rs
picky-asn1/src/wrapper.rs
picky-server/Cargo.toml
picky/Cargo.toml
picky/src/x509/certificate.rs
picky/src/x509/wincert.rs

Fix weird context-tag class.
- Remove `Tag::APP_{0-15}`
- Remove `Tag::CTX_{0-15}`
- Remove `Tag::application`
- Remove `Tag::context_specific`
- Rename `Tag::number` into `Tag::inner`
- Rename `ApplicationTag{0-15}` into `ExplicitContextTag{0-15}`
- Rename `ContextTag{0-15}` into `ImplicitContextTag{0-15}`
- Rename `Implicit` into `Optional`
- Add `Tag::is_primitive`
- Add `Tag::application_primitive`
- Add `Tag::application_constructed`
- Add `Tag::context_specific_primitive`
- Add `Tag::context_specific_constructed`
- Add `Tag::number`
- Add `Tag::class`
- Add `Tag::class_and_number`
- Add `Tag::components`
- Add `Tag::is_application`
- Add `Tag::is_context_specific`
- Add `Tag::is_universal`
- Add `Tag::is_private`
- Add `Tag::is_constructed`
- Add `Tag::is_primitive`
- Add …

Stopgap fix for #91

---

Cargo.lock
picky-asn1-x509/CHANGELOG.md
picky-asn1-x509/src/attribute.rs
picky-asn1-x509/src/oids.rs
picky-asn1-x509/src/pkcs7.rs
picky-asn1-x509/src/pkcs7/content_info.rs
picky-asn1-x509/src/pkcs7/timestamp.rs
picky-server/CHANGELOG.md
picky-server/Cargo.toml
picky-server/src/db/file.rs
picky-server/src/db/memory.rs
picky-server/src/db/mod.rs
picky-server/src/db/mongodb/mod.rs
picky-server/src/db/mongodb/model.rs
picky-server/src/http/controller.rs
picky-signtool/Cargo.toml
picky-signtool/src/config.rs
picky-signtool/src/sign.rs
picky-signtool/src/verify.rs
picky/CHANGELOG.md
picky/Cargo.toml
picky/src/signature.rs
picky/src/x509/pkcs7/authenticode.rs
picky/src/x509/pkcs7/ctl.rs
picky/src/x509/pkcs7/mod.rs
picky/src/x509/pkcs7/timestamp.rs

Added support for Authenticode timestamping for picky-signtool, and made Authenticode TSA server from picky-server.
There are two Authenticode timestamp protocols:
1) "Default" - https://docs.microsoft.com/en-us/windows/win32/seccrypto/time-stamping-authenticode-signatures.
2) RFC3161
I have implemented the first one, but I was keeping in mind that we might add the second one. For Authenticode TSA server with default protocol, we don't need to use the database, but I added counting issued Authenticode timestamps as RFC3161 requires it, and we might add support for RFC3161 someday.
For timestamping Authenticode signature with picky-singtool, somebody should add `--timestamp <Authenticode TSA server URL>` arg.

Authenticode timestamping

---

picky-signtool/Cargo.toml
picky-signtool/src/config.rs
picky/src/x509/pkcs7/authenticode.rs

Fix that we cannot sign with just an end-entry self-signed root certificate.
Fix that `output` CLI parameter is required for verifying a binary.

Fix Authenticode bugs that were found by QA

---

.github/workflows/ci.yml

Finish the picky build in GitHub workflow. Build and tests are run in parallel on both Windows and Linux. The minimum rust version check runs after the build; this means we still have usable artifacts even if the workflow fails.
This won't replace AZ pipelines until we port the release pipeline over.

GitHub workflow

---

picky/src/ssh/certificate.rs

I made an error that `cert_key_type` was deserialized twice while computing an `SSH` certificate signature while rebasing the ssh-ca branch to the latest master. This makes our `SSH` certificates' signatures incorrect. This PR fixes this.

Fix SSH certificate signature generation

---

picky-asn1-x509/src/name.rs
picky-signtool/src/lib.rs
picky-signtool/src/main.rs
picky-signtool/src/sign.rs
picky-signtool/src/verify.rs
picky/src/x509/name.rs
picky/src/x509/pkcs7/authenticode.rs

1. picky-signtool:
- Fix that `LIEF` logs can appear while verifying a binary(even with binary logging turn off).
- Fix incorrect behavior of `ca` flags
2. picky Authenticode related code:
- Fix a chain verification if the chain also contains timestamp certificates
- Add parsing of `GeneralName::OtherName` as missing it causes incorrect validation of some binaries.

Authenticode timestamping bug fixes

---

picky-asn1-x509/src/algorithm_identifier.rs
picky-asn1-x509/src/macros.rs
picky-asn1-x509/src/oids.rs
picky-asn1-x509/src/private_key_info.rs
picky-asn1-x509/src/subject_public_key_info.rs
picky-asn1/src/bit_string.rs
picky-asn1/src/wrapper.rs
picky/src/key.rs
picky/src/x509/certificate.rs

I added `EC` private keys encoding/decoding in `picky-asn1-x509`, support of `PrivateKey` to accept `EC` private keys.   
I will continue working on making `PrivateKey` API for `EC` private keys similar to the `RSA` ones, also on supporting `EC` signature. But, I will take some time to make myself more familiar with elliptic curves.  
This PR partially closes #100.

Elliptic curve private keys initial support 

---

picky-server/src/http/middleware.rs

When making a cross-origin request, browsers need to make a preflight request (with the OPTIONS verb) to check if a CORS header is allowing it. The Access-Control-Max-Age lets browser cache the preflight response, reducing the number of OPTIONS requests that are needed. The value is set to 2 hours (7200 seconds) which is the maximum value allowed by Chrome.

Add Access-Control-Max-Age to cache CORS preflight request responses

---

picky-asn1-der/src/application_tag.rs
picky-asn1-der/src/de/mod.rs
picky-asn1-der/src/lib.rs
picky-asn1-der/src/misc.rs
picky-asn1-der/src/ser/mod.rs
picky-asn1/src/tag.rs
picky-asn1/src/wrapper.rs

KDC proxy in DG related improvements:
- Added `ApplicationTag<V, const T: u8>` for easier using needed `ApplicationTagN` without adding a lot of new `ApplicationTag`s.
- Added `GENERAL_STRING`.
- Added `impl<T: Default> Default for Optional<T>`.
- Added clearing `encapsulator_tag_stack` as otherwise, it would contain unwanted tags on the next serialization.

KDC proxy in DG related improvements

---

picky-signtool/src/verify.rs
picky/src/x509/pkcs7/authenticode.rs

`Authenticode` timestamp protocol that we implemented places the timestamp certificates chain right after the signature certificates chain. But some signature certificates validations didn't handle such situations(or couldn't). So it added a specified `SignatureCertificatesIterator` iterator that filters out timestamp certificates and uses it where we expect only signature certificates. Also, I rewrite some functions to accept an iterator as a parameter.

Fix verifying an Authenticode signature certificates chain with timestamp certificates chain

---

Cargo.lock
picky/Cargo.toml
picky/src/http/http_signature.rs
picky/src/key.rs
picky/src/signature.rs
picky/src/ssh/certificate.rs
picky/src/x509/certificate.rs
picky/src/x509/csr.rs

This PR introduces support for handling certificates using elliptic curve public keys.
~~Only signature verification is currently implemented.~~
**Update:** Both signature creation and verification are supported.
The implementation relies on the `ring` crate, which currently is the only one capable of supporting both ECDSA p256 and ECDSA p384.
~~I haven't yet extended the unit tests. I'm looking forward to hear your feedback about this contribution. I think this is something you're interested about (see #100). I wonder if this is going in the direction you like.~~
**Update:** The unit tests have been extended too

Handle verification of keys using elliptic curve

---

Cargo.lock
picky-asn1-der/Cargo.toml
picky-asn1-der/README.md
picky-asn1-x509/CHANGELOG.md
picky-asn1-x509/Cargo.toml
picky-asn1-x509/README.md
picky-asn1/Cargo.toml
picky-asn1/README.md
picky-server/Cargo.toml
picky-server/src/db/file.rs
picky-signtool/Cargo.toml
picky-signtool/src/config.rs
picky-signtool/src/lib.rs
picky-signtool/src/main.rs
picky-signtool/src/utils.rs
picky-signtool/src/verify.rs
picky/CHANGELOG.md
picky/Cargo.toml
release.toml

Also: initial configuration for [`cargo-release`](https://github.com/crate-ci/cargo-release).
cc @flavio

Release chores (picky-asn1-x509 0.7.0 and picky 7.0.0-rc.1)

---

picky-server/src/http/authorization.rs
picky-server/src/http/controller.rs
picky/CHANGELOG.md
picky/src/jose/jwt.rs

This makes API more convenient to first process header and then decide what kind of validation should be applied, or what claims type to deserialize into.

Separate JWT validation from decoding in JOSE API

---

picky-asn1-der/src/application_tag.rs
picky-asn1-x509/src/oids.rs

`picky-asn1-der`:
* Improved the const-generic `ApplicationTag`: make inner value public and add requiring the `Clone` trait.
`picky-asn1-x509`:
* Add NLA protocols OIDs.

Some improvements regarding Kerberos module in sspi-rs

---

picky-krb/src/constants.rs

Add missing Kerberos name type constants (https://www.rfc-editor.org/rfc/rfc4120#section-7.5.8) which we'll need in sspi-rs to handle NT_PRINCIPAL (1) and NT_ENTERPRISE (10) name types [based on the username formats (netbios versus UPN)](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-kile/6435d3fb-8cf6-4df5-a156-1277690ed59c). We can temporarily just hardcode the value in sspi-rs until the next release of picky-krb.

picky-krb: add missing Kerberos name type constants

---

Cargo.lock
ffi/wasm/Cargo.toml
ffi/wasm/publish.ps1

This gives the best user experience when using frameworks such as Angular and React

fix(wasm): use `bundler` target

---

.github/workflows/npm-publish.yml
.github/workflows/nuget.yml

The inputs need to be under the `inputs` key.

ci: actually fix dry run

---

ffi/wasm/Cargo.lock
ffi/wasm/Cargo.toml
ffi/wasm/README.md
ffi/wasm/publish.ps1
ffi/wasm/src/lib.rs

`wee_alloc` crate is currently unmaintained and has a few open issues. In particular, one of these issue is an unbounded memeroy leak. As such, we stop considering this crate as production-ready and switch to the default Rust standard allocator in newer NPM packages.
- https://github.com/rustwasm/wee_alloc/issues/106
- https://github.com/rustwasm/wee_alloc/issues/107
- https://rustsec.org/advisories/RUSTSEC-2022-0054.html
Issue: ARC-98

fix(picky-wasm): [SECURITY] remove wee_alloc dependency

---

Cargo.lock
ffi/Cargo.toml
ffi/dotnet/Devolutions.Picky/Devolutions.Picky.csproj
ffi/dotnet/Devolutions.Picky/Devolutions.Picky.props
ffi/dotnet/Devolutions.Picky/Devolutions.Picky.targets
ffi/dotnet/Devolutions.Picky/Generated/RawDateFfiResultBoxUtcDateBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawDateFfiResultI64BoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawJwtFfiResultBoxJwtSigBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawJwtFfiResultVoidBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawKeyFfiResultBoxPemBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawKeyFfiResultBoxPrivateKeyBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawKeyFfiResultBoxPublicKeyBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawPemFfiResultBoxPemBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawPemFfiResultVoidBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawSignatureFfiResultBoxSignatureAlgorithmBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawSignatureFfiResultVoidBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawSshFfiResultBoxPemBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawSshFfiResultBoxSshCertBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawSshFfiResultBoxSshPrivateKeyBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawSshFfiResultBoxSshPublicKeyBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawSshFfiResultVoidBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawX509FfiResultBoxCertBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawX509FfiResultBoxPemBoxPickyError.cs
ffi/dotnet/Devolutions.Picky/Generated/RawX509FfiResultVoidBoxPickyError.cs
ffi/justfile

- Add missing library redirections
- Link the native library in a .props file (this seems to resolve some issues reported by RDM team around building)

Fix native library issues for iOS

---

.github/workflows/nuget.yml

Avoid potential issue if a dependent crate considers `IPHONEOS_DEPLOYMENT_TARGET` even when building for macOS.

Conditionally set Apple deployment target

---

ffi/dotnet/Devolutions.Picky.Tests/PemTests.cs
ffi/dotnet/Devolutions.Picky/Devolutions.Picky.csproj
ffi/dotnet/Devolutions.Picky/src/Pem.Addons.cs
ffi/src/pem.rs

Until array support is added to diplomat, we do the FFI dance manually.

feat(dotnet): support returning Pem data

---

.github/workflows/npm-publish.yml
.github/workflows/nuget.yml
.github/workflows/release.yml
ffi/dotnet/Devolutions.Picky/Devolutions.Picky.Build.iOS.props
ffi/dotnet/Devolutions.Picky/Devolutions.Picky.csproj
ffi/dotnet/Devolutions.Picky/Devolutions.Picky.iOS.props
ffi/dotnet/Devolutions.Picky/Devolutions.Picky.targets

On Android, the check for `IsAndroid` in MSBuild appeared valid but wasn't working for some reason under net6.0-android targets. This causes the `NativeReference` element to be evaluated on that platform, and MSBuild would try to link the macOS .dylib. Changing the condition to check the current TargetFramework for "Android" seems to work well everywhere.
On iOS, the net7.0-ios target is rolled back to net6.0-ios for better compatibility. I removed the bare .dylibs from the package - `dotnet build` seems to pick up the references at packaging time and then fails because of "duplicate resource keys". Since we don't use the bare .dylibs, I just removed them from the package. Next, there were build failures consuming the package in net6.0-ios and net7.0-ios targets - the linker was unable to …

Fixes for mobile nuget

---

ffi/dotnet/Devolutions.Picky/Devolutions.Picky.csproj
ffi/dotnet/Devolutions.Picky/Devolutions.Picky.targets

`dotnet build` will look for native dependencies in the _runtimes_ path and `lipo` them automatically if needed.

fix(ffi): link thin binaries on macOS net6 targets

---

ffi/dotnet/Devolutions.Picky/Devolutions.Picky.csproj
ffi/dotnet/Devolutions.Picky/Devolutions.Picky.targets

Previous changes made faulty assumptions
On net6-macos; the build system seems capable of picking up the shared libraries from the `runtimes` path _without_ needing to declare them as `NativeReferences`
However, we need to avoid it trying to link the universal shared library used under the Xamarin.Mac target.

fix(ffi): Fix net6-macos packaging

---

Cargo.lock
ffi/Cargo.toml
ffi/src/x509.rs
ffi/wasm/Cargo.lock
picky-asn1-der/Cargo.toml
picky-asn1-x509/Cargo.toml
picky-asn1-x509/src/certificate.rs
picky-asn1/Cargo.toml
picky-asn1/src/date.rs
picky-krb/Cargo.toml
picky-krb/src/crypto/checksum.rs
picky-signtool/Cargo.toml
picky/CHANGELOG.md
picky/Cargo.toml
picky/src/jose/jwe.rs
picky/src/jose/jws.rs
picky/src/pem.rs
picky/src/ssh/encode.rs
picky/src/x509/certificate.rs
picky/src/x509/pkcs7/authenticode.rs
picky/src/x509/wincert.rs
rust-toolchain.toml

General maintenance of the project and preparing publication of the next release candidate of `picky` crate (`v7.0.0.rc-4`).
Enable all features when generating documentation on docs.rs (see https://github.com/Devolutions/picky-rs/issues/203#issuecomment-1436117513)

chore(picky): prepare release (v7.0.0-rc.4)

---

Cargo.lock
picky/Cargo.toml
picky/src/key/ec.rs
picky/src/signature.rs

Hi, I'm working on the downstream crates and find that the `ring` crate used in this crate cannot be compiled in arch `s390x`. Thus I summit this PR to replace the `ring` with RustCrypto to implement Elliptic Curve Signatures.
Please take a look if I did anything contrary to the design of this module. Thanks!
- Replaced `ring` elliptic curve signature implementations with RustCrypto
- Added a compability test for previous ring implementation and current rust crypto to ensure the functionality of API does not change
cc @flavio who is the initial writer of the related code

Replace ring ecdsa implementation with rust cryptos

---

picky-asn1/src/wrapper.rs

Validation of ASN1.Integer in Go code was failing due to the encoding not being minimal, and the spec indicates that it is required to be minimal.

ASN.1 Integer minimal encoding is required per X.690-0207 Section 8.3.2

---

picky-asn1-x509/src/algorithm_identifier.rs
picky-asn1-x509/src/oids.rs

Note that the deserializer assumes all fields are specified in the ASN.1 structure and none are using the default. Given that SHA1 is considered broken, and that all default fields only make sense in the context of SHA1, no effort has been made to support the DEFAULTs.

Serialize and deserialize RSASSA-PSS AlgorithmIdentifier.

---

picky-asn1/Cargo.toml
picky/Cargo.toml

Enabling the default features of chrono causes the time 0.1 crate to be added as a transitive dependency.
This old version of time is affected by [CVE RUSTSEC-2020-0071](https://rustsec.org/advisories/RUSTSEC-2020-0071).
Thanks to work done inside of chrono 0.4, there are high chances the majority of the codebases do not actually need it. Which is exactly the case for picky.

chore(deps): do not enable default features of chrono

---

picky-asn1-der/Cargo.toml
picky-asn1-der/LICENSE-APACHE
picky-asn1-der/LICENSE-MIT
picky-asn1-x509/LICENSE-APACHE
picky-asn1-x509/LICENSE-MIT
picky-asn1/LICENSE-APACHE
picky-asn1/LICENSE-MIT
picky-krb/Cargo.toml
picky-krb/LICENSE-APACHE
picky-krb/LICENSE-MIT
picky/Cargo.toml
picky/LICENSE-APACHE
picky/LICENSE-MIT

I've added symbolic links to the license files to all workspace members that don't have `package.publish = false` set in their Cargo.toml file, and adapted `package.include` settings to include these files where necessary. I've tested the change locally, and `cargo package` included the license texts in `.crate` tarballs as intended.
Fixes #230

chore: include license files in published crates

---

picky-asn1-x509/src/oids.rs
picky-krb/src/constants.rs
picky-krb/src/credssp.rs
picky-krb/src/lib.rs

Hello,
During the Kerberos smart card logon, the smart card credentials are transferred using the `TsSmartCardCreds` and `TsCspDataDetail` structures.
The password-based credentials are encoded using the [`ber`](https://github.com/Devolutions/sspi-rs/tree/master/src/ber) module in the `sspi-rs`. But now we have `picky-*` crates for the `asn1` encoding. So, I decided to add CredSSP-related constants and credentials structures to the `picky-krb` crate.
Docs and reference:
* [TSCredentials](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-cssp/94a1ab00-5500-42fd-8d3d-7a84e6c2cf03)
* [TSPasswordCreds](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-cssp/17773cc4-21e9-4a75-a0dd-72706b174fe5)
* [TSSmartCardCreds](https://learn.microsoft.com/en-us/openspecs/window …

picky-krb: CredSSP credentials structures

---

ffi/dotnet/Devolutions.Picky/Devolutions.Picky.targets

Don't use `NativeReference` in the targets file on macOS when targeting dotnet

fix(ffi): Fix netcore packaging on macOS targets

---

Cargo.lock
ffi/wasm/Cargo.lock
picky-asn1/src/date.rs
picky/src/x509/pkcs7/authenticode.rs

Address the following dependabot alerts : 
https://github.com/Devolutions/picky-rs/security/dependabot/29
https://github.com/Devolutions/picky-rs/security/dependabot/28
https://github.com/Devolutions/picky-rs/security/dependabot/27

chore(deps): Cargo update

---

ffi/src/pkcs12.rs
picky-asn1-der/src/ser/mod.rs
picky-krb/src/crypto/aes/aes128_cts_hmac_sha1_96.rs
picky-krb/src/crypto/aes/aes256_cts_hmac_sha1_96.rs
picky-krb/src/crypto/des/des3_cbc_sha1_kd.rs
picky-krb/src/negoex/mod.rs
picky/src/jose/jwe.rs
picky/src/key/mod.rs
picky/src/pkcs12/encryption.rs
picky/src/pkcs12/safe_bag.rs
picky/src/x509/pkcs7/authenticode.rs
rust-toolchain.toml

update Rust toolchain versoin to 1.70.0, as it is the minimum version needed to run `just diplomat-install` in ffi crate.
Fixed new clippy waring

chore: update rust toolchain version

---

ffi/wasm/README.md
ffi/wasm/main.ts
ffi/wasm/package.json
ffi/wasm/publish.ps1
ffi/wasm/vite.config.ts

Use Vite to rebuild Picky WASM into Base64 encoded JavaScript. This approach have the following benefits for angular 18:
1. Import and use, no extra configuration
In Angular 18, if we want to use WASM, we need to configure Vite (that is used bu Angular 18) to use [vite-plugin-wasm](https://www.npmjs.com/package/vite-plugin-wasm).
2. Zero interface change
3. Backward compatibility
As it is just JavaScript file, any project can just import it without worrying about how to load WASM

build(wasm): use vite to embed the WASM module in base64

---

.github/workflows/nuget.yml

Avoiding macos-13 and macos-14 for now, as it requires selecting an Intel or Apple Silicon runner.

ci: update macos runner version

---

ffi/wasm/.gitignore
ffi/wasm/Cargo.lock
ffi/wasm/Cargo.toml
ffi/wasm/README.md
ffi/wasm/main.ts
ffi/wasm/package.json
ffi/wasm/rewrite-location.js
ffi/wasm/vite.config.ts

- Update from vite 4 to vite 5
- Adjust package metadata
- Improve dts bundling (single file instead of two)
- Include UMD (Universal Module Definition) too
Package tree before this patch:
```bash
$ tree package
package
├── dist
│   ├── main.d.ts
│   ├── picky.js
│   └── pkg
│       └── picky.d.ts
├── package.json
└── README.md
```
Package tree after this patch:
```bash
$ tree package
package
├── dist
│   ├── picky.d.ts
│   ├── picky.js
│   └── picky.umd.cjs
├── package.json
└── README.md
```

build(wasm): clean up npm package

---

Cargo.lock
ffi/Cargo.toml
ffi/wasm/Cargo.lock
picky-asn1-der/CHANGELOG.md
picky-asn1-der/Cargo.toml
picky-asn1-x509/CHANGELOG.md
picky-asn1-x509/Cargo.toml
picky-asn1/CHANGELOG.md
picky-asn1/Cargo.toml
picky-krb/CHANGELOG.md
picky-krb/Cargo.toml
picky/CHANGELOG.md
picky/Cargo.toml

Crates to release:
- picky-asn1 -> 0.9.0
- picky-asn1-der -> 0.5.0
- picky-asn1-x509 -> 0.13.0
- picky-krb -> 0.9.0
- picky -> 7.0.0-rc.9

chore: prepare releases

---

.github/workflows/nuget.yml

The Android 19 toolchain is not included anymore, so we bump the minimum supported version to Android 21 for i686 (x86) architecture.

ci(nuget): fix build for Android

---

.github/workflows/nuget.yml

The macOS 12 runner image will be removed by December 3rd, 2024

ci: update macos-12 runners to macos-14

---

ffi/dotnet/Devolutions.Picky/Generated/Pkcs12MacAlgorithmHmac.cs
ffi/dotnet/Devolutions.Picky/Generated/RawPkcs12MacAlgorithmHmac.cs
ffi/src/pkcs12.rs

The `Iterations` getter on Pkcs12MacAlgorithm doesn't build in dotnet:
> error CS0266: Cannot implicitly convert type 'uint*' to 'uint?'. An explicit conversion exists (are you missing a cast?)
I'm unsure right now how to fix this in diplomat, but the field seems to just be for completeness / an implementation detail. So for now, I remove it from the FFI interface.

fix(ffi): remove Pkcs12Mac iterations from FFI interface

---

picky-asn1-x509/src/algorithm_identifier.rs

Hi,
In this pull request, I've improved the `AlgorithmIdentifier` parsing. Now, we allow the use of an AES identifier without any parameters.
We need it to parse the `EnvelopedData` structure (I will add it in the next PR).
For example, here is an example of the AES identifier without parameters ([link](https://crypto.qkation.com/asn1/?asn1=a2820402020104308203c40482036c010000004b44534b0300000069010000100000000300000071c278d72590829af6dcb8960b8ad8c5080300001800000018000000444850420001000087a8e61db4b6663cffbbd19c651959998ceef608660dd0f25d2ceed4435e3b00e00df8f1d61957d4faf7df4561b2aa3016c3d91134096faa3bf4296d830e9a7c209e0c6497517abd5a8a9d306bcf67ed91f9e6725b4758c022e0b1ef4275bf7b6c5bfc11d45f9088b941f54eb1e59bb8bc39a0bf12307f5c4fdb70c581b23f76b63acae1caa6b7902d52526735488a0ef13c6d9a51bfa4ab3ad …

fix(picky-asn1-x509): improve algorithm identifier parsing

---

picky-asn1-x509/src/algorithm_identifier.rs

Hi,
In this PR, I've implemented the `AesAuthEncParams::new` method. We need it in `sspi-rs` for DPAPI blob testing.

feat(picky-asn1-x509): `AesAuthEncParams::new` method

---

.gitignore
copy-license-files.ps1
picky-asn1-der/LICENSE-APACHE
picky-asn1-der/LICENSE-MIT
picky-asn1-x509/LICENSE-APACHE
picky-asn1-x509/LICENSE-MIT
picky-asn1/LICENSE-APACHE
picky-asn1/LICENSE-MIT
picky-krb/LICENSE-APACHE
picky-krb/LICENSE-MIT
picky-test-data/LICENSE-APACHE
picky-test-data/LICENSE-MIT
picky/LICENSE-APACHE
picky/LICENSE-MIT

Use symlinks instead of copying files to avoid a “dirty” state during cargo publish and preserve VCS info. With #337 merged, CI handles publishing consistently, so developer environments no longer matter.

fix: symlinks to license files in packages

---

picky-krb/src/crypto/aes/aes128_cts_hmac_sha1_96.rs
picky-krb/src/crypto/aes/aes256_cts_hmac_sha1_96.rs
picky-krb/src/crypto/aes/decrypt.rs
picky-krb/src/crypto/aes/encrypt.rs
picky-krb/src/crypto/aes/mod.rs
picky-krb/src/crypto/cipher.rs
picky-krb/src/crypto/common.rs
picky-krb/src/crypto/des/decrypt.rs
picky-krb/src/crypto/des/des3_cbc_sha1_kd.rs
picky-krb/src/crypto/des/encrypt.rs
picky-krb/src/crypto/mod.rs

Hi,
I added the possibility of Kerberos encryption but without a checksum. We need this functionality to support `SECBUFFER_READONLY` and `SECBUFFER_READONLY_WITH_CHECKSUM` flags for security buffers in `sspi-rs`. Related to: https://github.com/Devolutions/sspi-rs/issues/120 
Additionally, I reviewed the `crypto` module in `picky-krb`. It seems like Kerberos encryption algorithms were implemented a long time ago. We can refactor it by using [`cts`](https://docs.rs/cts/latest/cts/) and [`aes`](https://docs.rs/aes-gcm/latest/aes_gcm/) crates and get rid of the custom `cts` mode implementation. Let's create an issue for the future.
Docs & reference:
* [`SecBuffer` structure (sspi.h)](https://learn.microsoft.com/en-us/windows/win32/api/sspi/ns-sspi-secbuffer).

feat(picky-krb): implement Kerberos encryption without a checksum

---

picky-krb/src/crypto/aes/aes128_cts_hmac_sha1_96.rs
picky-krb/src/crypto/aes/aes256_cts_hmac_sha1_96.rs
picky-krb/src/crypto/cipher.rs
picky-krb/src/crypto/des/des3_cbc_sha1_kd.rs

Hi,
I implemented the `encryption_checksum` method for Kerberos ciphers. We need it to generate the Kerberos encryption checksum. However, the encryption checksum and regular Kebreros checksum key derivation methods are different. I added a comment with an explanation in the code.

feat(picky-krb): implement `encryption_checksum` for krb ciphers

---

picky/src/http/http_signature.rs
picky/src/http/mod.rs

Not sure if picky is attempting to be compliant with "draft-cavage-http-signatures-12" (i.e. the algorithm used throughout the Fediverse), or not. If so, the request target field in the signing string gets its own "pseudo-header name": `(request-target)`. This PR changes that & updates the test suite accordingly.
Commit message follows:
For reasons unclear to me, the `http-signature` module treats the request target specially in that it is added to & read from the signing string with no header name (unlike, say, `(created)` or `(expires)`). As we see [here](https://datatracker.ietf.org/doc/html/draft-cavage-http-signatures-12#page-9), it, too,  has a "psuedo-header" name: `(request-target)`.
It's absence from the signing string was breaking my attempts to use picky to validate message …

fix(picky)!: comply with draft-cavage-http-signatures-12 when signing HTTP messages

---

picky-krb/src/data_types.rs
picky-krb/src/messages.rs

Hi,
I implemented `EncTicketPart` structure in the `picky-krb` crate. We need this structure to be able to implement KDC mock. More details: https://github.com/Devolutions/sspi-rs/pull/429

feat(picky-krb): implement `EncTicketPart`

---

picky-krb/src/data_types.rs

Hi,
I noticed that we have a typo in the `AuthenticatorInner` field name.

fix(picky-krb): typo in `AuthenticatorInner::authenticator_vno`

---

picky-asn1-x509/src/private_key_info.rs

The Drop implementation of the RsaPrivateKey struct was only partially zeroizing the secrets.
Security: yes

fix(picky-asn1-x509): properly zeroize RsaPrivateKey

---

.github/workflows/nuget.yml
Cargo.toml

Aim for good balance between size and performance.
- Baseline: 7.4M
- strip = "symbols": 6.0M
- lto = true: 4.7M
- opt-level = "z": 3.5M
- codegen-units = 1: 3.3M
- panic = "abort": 3.0M
- opt-level = 3 for crypto libs: 3.1M

build: optimize binary size for FFI builds

---

.github/workflows/nuget.yml

Fixes the following warning:
```
warning: deployment target in MACOSX_DEPLOYMENT_TARGET was set to 10.10, but the minimum supported by `rustc` is 10.12
```

ci(nuget): set MACOSX_DEPLOYMENT_TARGET to 10.12

---

Cargo.lock
picky/Cargo.toml

Finally, unblocks the next release of picky-rs crates.

fix: use published `rc2` version

---

Cargo.lock
ffi/wasm/Cargo.lock
picky-krb/Cargo.toml
picky/Cargo.toml
picky/src/signature.rs

The patch version upgrade is not allowed to bring breaking changes, but this rule doesn't work for an `rc` version. So we should pin the `rc` versions, to not allow _cargo_ update to a new `rc` automatically. 
Seems like RustCrypto will have release of all crates (really soon)[https://github.com/RustCrypto/AEADs/issues/726#issuecomment-3348738331]. This hotfix won't live a long time. Here is the tracking issue for it - https://github.com/RustCrypto/traits/issues/1571. 
Fixes #416.

fix: pin RustCrypto release candidate crates
