Devolutions/picky-rs

- Cargo.lock
- picky-server/Cargo.toml
Color in log is a problem with datadog. We remove color from saphir.
> wayk-1735 - Removed color from logs

- ci/azure-pipelines.yaml
- setup-git-hooks.sh
Add a script to setup git hook to get an automatic formatting check on commit.
Update Linux CI to also check formatting and tests. Build is still taking less time than Windows build.
> Git hook + formatting and tests check in CI

- Cargo.lock
> Run `cargo update` for backtrace-rs patch

- Cargo.lock
- picky-server/Cargo.toml
Version 4.3.0 has been released. Moving to next version...
> Version bump from 4.3.0 to 4.4.0

- picky/src/algorithm_identifier.rs
Fixing the implementations of AES and SHA object identifiers by adding
the parameters they need. Also added a few unit tests for them.
Signed-off-by: Ionut Mihalcea <ionut.mihalcea@arm.com>
> Fix implementations of object identifiers

- Cargo.lock
- ci/azure-pipelines.yaml
- picky-server/Cargo.toml
- picky-server/src/http/authorization.rs
- picky-server/src/http/controller.rs
- picky/CHANGELOG.md
- picky/Cargo.toml
- picky/src/algorithm_identifier.rs
- picky/src/http/http_request.rs
- picky/src/http/http_signature.rs
- picky/src/http/mod.rs
- picky/src/jose/jwt.rs
- picky/src/x509/certificate.rs
All breaking changes are included in this release.
> Picky lib 5.0.0

- Cargo.lock
- pester/Picky.Tests.ps1
- pester/Private/RunPicky.ps1
- picky-asn1-x509/README.md
- picky-server/CHANGELOG.md
- picky-server/src/cli.yml
- picky-server/src/config.rs
- picky-server/src/http/authorization.rs
- picky-server/src/http/controller.rs
- picky/CHANGELOG.md
- picky/Cargo.toml
- picky/src/x509/certificate.rs
cf: WAYK-2038 ticket in bitbucket.
> No more api key

- picky-asn1-x509/src/attribute_type_and_value.rs
- picky-asn1-x509/src/name.rs
- picky-asn1-x509/src/oids.rs
- picky/src/x509/certificate.rs
- picky/src/x509/name.rs
- picky/tests/mkcert_all_stars.rs
> Improve Subject/Issuer name attributes an organization spelling

- Cargo.lock
- picky-asn1-x509/CHANGELOG.md
- picky-asn1-x509/Cargo.toml
- picky-asn1-x509/src/algorithm_identifier.rs
- picky-asn1-x509/src/private_key_info.rs
- picky-server/Cargo.toml
- picky/CHANGELOG.md
- picky/Cargo.toml
- picky/src/jose/jwe.rs
- picky/src/key.rs
- picky/src/x509/certificate.rs
> Fix serial number generation and RSA's second exponent calculus

- picky-asn1-x509/src/algorithm_identifier.rs
- picky-asn1-x509/src/oids.rs
- picky-asn1-x509/src/subject_public_key_info.rs
- picky/src/jose/jwk.rs
- picky/src/key.rs
- picky/src/x509/key_id_gen_method.rs
* Define OIDs from RFC8410
* Add support for Ed25519 AlgorithmIdentifier
* Add support for Ed25519 PublicKey(Info)
> picky-asn1-x509: basic support for EdDSA

- picky-asn1-der/Cargo.toml
- picky/Cargo.toml
Run [cargo-diet](https://github.com/the-lean-crate/cargo-diet)
> Run cargo-diet

- picky-asn1-x509/src/oids.rs
Signed-off-by: Ionut Mihalcea <ionut.mihalcea@arm.com>
> Add some ECC OIDs.

- Cargo.lock
- ci/azure-pipelines.yaml
- picky-server/src/http/controller.rs
- picky-server/src/picky_controller.rs
- picky/CHANGELOG.md
- picky/Cargo.toml
- picky/README.md
- picky/src/http/http_signature.rs
- picky/src/jose/jwe.rs
- picky/src/jose/jws.rs
- picky/src/key.rs
- picky/src/signature.rs
- picky/src/x509/certificate.rs
- picky/src/x509/key_id_gen_method.rs
Quick PR for updating rsa crate and fixing clippy warnings :slightly_smiling_face:
> Update rsa and clippy

- .github/workflows/ci.yml
- .github/workflows/release.yml
Initial release workflow. Details still need to be finalized, but the yml file must exist on main branch to be able to run and iterate on it.
> Add release workflow

- .github/workflows/ci.yml
- .github/workflows/release.yml
Final release pipeline to build containers and push to Docker Hub
> Release pipeline

- .github/workflows/nuget.yml
Next: properly package the native libraries into the nuget package
> Nuget package (native build)

- picky/src/key.rs
This fixes the issue described here: https://github.com/Devolutions/picky-rs/issues/100#issuecomment-1118363996
> Fetch curve info from private_key_algorithm

- picky/src/jose/jwe.rs
Quick notes:
For the NonceSize and TagSize, the values are hardcoded because the cbc crate is not imported at all, so I cannot fetch it from there.
> JWE code review

- .github/workflows/nuget.yml
We should make a dry run, but the same code runs on the dirty test branch
> Fix using latest Android NDK

- picky-asn1-x509/src/attribute_type_and_value.rs
- picky-asn1-x509/src/name.rs
- picky-asn1-x509/src/oids.rs
I wanted to add a phone number and given name
Closes #191
> Add given name and phone

- Cargo.lock
- ffi/wasm/Cargo.lock
- picky-asn1-der/Cargo.toml
- picky-asn1-x509/Cargo.toml
- picky-asn1/CHANGELOG.md
- picky-asn1/Cargo.toml
- picky-server/Cargo.toml
- picky/CHANGELOG.md
- picky/Cargo.toml
picky-asn1 v0.7.2
picky v7.0.0-rc.5
cc @Xynnn007 @brimworks 
Hi @brimworks, just letting you know that your mail address is hidden so I only added your name as displayed in your git commit but if you want to, don’t hesitate to open a PR and add it yourself :slightly_smiling_face:
> chore: prepare release

- ffi/dotnet/Devolutions.Picky.Tests/KeyTests.cs
- ffi/dotnet/Devolutions.Picky/Generated/PrivateKey.cs
- ffi/dotnet/Devolutions.Picky/Generated/RawPrivateKey.cs
- ffi/src/key.rs
- ffi/wasm/src/key.rs
- picky/src/key/mod.rs
I added a few additional smoke tests for sanity, though it didn’t uncover any issue
Issue: ARC-172
> test(ffi): cover key generation

- .github/workflows/nuget.yml
- ffi/dotnet/Devolutions.Picky/Devolutions.Picky.Build.iOS.props
> ci: fix iOS managed build

- picky-krb/README.md
This is nothing spectacular, but could help point other folks in generally the right direction when trying to utilize this crate.
> docs(picky-krb): add a minimal README.md file

- ffi/wasm/Cargo.lock
Update cargo.lock file to dismiss https://github.com/Devolutions/picky-rs/security/dependabot/42 in `ffi/wasm`
> chore(deps): Update cargo.lock in wasm

- picky-asn1-x509/src/algorithm_identifier.rs
- picky-asn1-x509/src/pkcs7/enveloped_data.rs
- picky-asn1-x509/src/pkcs7/mod.rs
Hi,
In this PR, I've implemented `EnvelopedData` and related structures. We need them to encode/decode DPAPI blobs properly.
> `feat(picly-asn1-x509)`: implement `EnvelopedData` and related structures

- picky-asn1-x509/src/oids.rs
Hi,
In this PR, I added the enveloped data OID. We need it for the correct DPAPI implementation.
> feat(picky-asn1-x509): add enveloped-data oid

- .github/workflows/release-crates.yml
- cliff.toml
- picky-asn1-der/CHANGELOG.md
- picky-asn1-x509/CHANGELOG.md
- picky-asn1/CHANGELOG.md
- picky/CHANGELOG.md
- release-plz.toml
Same as what is implemented for IronRDP.
> ci: automate crate publishing
